"""add order_number to all order tables

Revision ID: e9c7cd0f6068
Revises: fd8619064486
Create Date: 2026-06-08 02:58:06.356072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c7cd0f6068'
down_revision: Union[str, None] = 'fd8619064486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('order_number', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_deliveries_order_number'), 'deliveries', ['order_number'], unique=True)
    op.add_column('retail_orders', sa.Column('order_number', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_retail_orders_order_number'), 'retail_orders', ['order_number'], unique=True)
    op.add_column('return_orders', sa.Column('order_number', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_return_orders_order_number'), 'return_orders', ['order_number'], unique=True)
    op.drop_column('return_orders', 'source_order_id')
    op.drop_column('return_orders', 'source_type')
    op.add_column('subscription_orders', sa.Column('order_number', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_subscription_orders_order_number'), 'subscription_orders', ['order_number'], unique=True)
    op.add_column('wastage_orders', sa.Column('order_number', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_wastage_orders_order_number'), 'wastage_orders', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wastage_orders_order_number'), table_name='wastage_orders')
    op.drop_column('wastage_orders', 'order_number')
    op.drop_index(op.f('ix_subscription_orders_order_number'), table_name='subscription_orders')
    op.drop_column('subscription_orders', 'order_number')
    op.add_column('return_orders', sa.Column('source_type', sa.VARCHAR(length=20), nullable=True))
    op.add_column('return_orders', sa.Column('source_order_id', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_return_orders_order_number'), table_name='return_orders')
    op.drop_column('return_orders', 'order_number')
    op.drop_index(op.f('ix_retail_orders_order_number'), table_name='retail_orders')
    op.drop_column('retail_orders', 'order_number')
    op.drop_index(op.f('ix_deliveries_order_number'), table_name='deliveries')
    op.drop_column('deliveries', 'order_number')
    # ### end Alembic commands ###
